version: '3'
services:
  web:
    image: nginx:latest
    working_dir: /code
    ports:
      - "80:80"
    volumes:
      - ../:/code
      - ./nginx/admin.conf:/etc/nginx/conf.d/admin.conf
    links:
      - php

  php:
    build: php
    working_dir: /code
    volumes:
      - ../:/code

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - '1025:1025'
      - '8025:8025'







